apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.containerName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.containerName }}
    spec:
      containers:
        - name: {{ .Values.postgresql.containerName }}
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.service.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.db.name }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.db.password }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
